import { Shipment, MarketSpotPrice, VaultHolding } from './types'

export const initialMarketPrices: MarketSpotPrice[] = [
  { symbol: 'XAU/USD', name: 'Gold Spot', price: 2934.40, currency: 'USD', changePercent: +0.48, unit: 'ozt' },
  { symbol: 'XAG/USD', name: 'Silver Spot', price: 33.85, currency: 'USD', changePercent: +1.12, unit: 'ozt' },
  { symbol: 'XPT/USD', name: 'Platinum Spot', price: 986.20, currency: 'USD', changePercent: -0.22, unit: 'ozt' },
  { symbol: 'XPD/USD', name: 'Palladium Spot', price: 1028.50, currency: 'USD', changePercent: +0.65, unit: 'ozt' },
]

export const shipmentsData: Shipment[] = [
  {
    id: 'GOLD-2026-001245',
    trackingNumber: 'AV-DXB-GVA-99428-X',
    status: 'In Transit — Secure Air Corridor',
    statusType: 'in-flight',
    category: 'Precious Metals & Bullion',
    origin: {
      city: 'Dubai',
      country: 'United Arab Emirates',
      facility: 'DMCC Vault Alpha-4 (Dubai Multi Commodities Centre)',
      code: 'DXB-V04',
      coords: [25.2048, 55.2708],
    },
    destination: {
      city: 'Geneva',
      country: 'Switzerland',
      facility: 'Geneva Freeport High-Security Vault Complex B-12',
      code: 'GVA-FP12',
      coords: [46.2044, 6.1432],
    },
    currentLocation: {
      name: 'Central European Transit Airspace (Overflight Corridor E-04)',
      coords: [45.4642, 9.1900],
      statusText: 'Cruising FL380 • Armed Specie Escort Monitored',
    },
    eta: 'Today, 18:45 CET',
    dispatchedAt: '14 Mar 2026, 06:15 UTC+4',
    progress: 68,
    transportMode: 'Chartered Air-Specie Convoy (Flight EK-089)',
    carrierFlightNumber: 'EK-089 / SPECIE-SECURE',
    custodyOfficer: 'Senior Officer M. Al-Mansoor (ID: #DXB-9021)',
    clientCode: 'CLIENT-STERLING',
    checkpoints: [
      {
        id: 'cp-1',
        timestamp: '14 Mar 2026, 06:15 UTC+4',
        title: 'Vault Release & Dual Custody Handover',
        location: 'Dubai, UAE',
        facility: 'DMCC Vault Alpha-4',
        status: 'completed',
        officer: 'T. Rashid & M. Al-Mansoor',
        officerId: 'DMCC-SEC-4410',
        sealId: 'SEAL-DXB-99428-A',
        hash: 'SHA256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
        notes: 'Dual biometric biometric safe unlock confirmed. Bars weighed, laser-scanned and verified against assay register.',
      },
      {
        id: 'cp-2',
        timestamp: '14 Mar 2026, 07:30 UTC+4',
        title: 'Armored Convoy Transfer to Airside',
        location: 'Dubai International Airport',
        facility: 'VIP Cargo Apron Stand B-14',
        status: 'completed',
        officer: 'Commander D. Thorne',
        officerId: 'G4S-TACTICAL-08',
        sealId: 'SEAL-DXB-99428-B',
        hash: 'SHA256:4a35edd8b5a4ef6551b9e02ef252f4c3983228f44d9f67a2d815777777123456',
        notes: 'Reinforced Level IV armored convoy completed airside transit without anomaly. Perimeter security secured.',
      },
      {
        id: 'cp-3',
        timestamp: '14 Mar 2026, 09:10 UTC+4',
        title: 'Airside Cask Loading & Telemetry Activation',
        location: 'Dubai Airport Airside',
        facility: 'Specie Container Bay #3',
        status: 'completed',
        officer: 'Flight Security Lead E. Moreau',
        officerId: 'AV-AIR-229',
        sealId: 'AES-88401-CH',
        hash: 'SHA256:19b2210e77a45618b0292f7d38383f9821033282245b90293110291932910391',
        notes: 'IoT electronic tamper seal AES-88401-CH armed. Satellite telemetry downlink synchronized to Geneva Command.',
      },
      {
        id: 'cp-4',
        timestamp: '14 Mar 2026, 12:40 UTC',
        title: 'Swiss Neutral Airspace In-Flight Transfer',
        location: 'European Airspace',
        facility: 'Flight EK-089 (Alt: 38,000 ft)',
        status: 'current',
        officer: 'Captain R. Keller & Specie Marshal H. Weber',
        officerId: 'SWISS-SPECIE-04',
        sealId: 'AES-88401-CH (ACTIVE)',
        hash: 'SHA256:990184bba1728491028374619283746192837461928374619283746192837461',
        notes: 'Active radar lock maintained. All IoT environmental and G-force sensors nominal. Zero tamper events recorded.',
      },
      {
        id: 'cp-5',
        timestamp: '14 Mar 2026, 17:15 CET (Estimated)',
        title: 'Geneva Cointrin Airport Airside Reception',
        location: 'Geneva, Switzerland',
        facility: 'Geneva Airport High-Security Apron',
        status: 'pending',
        officer: 'Chief Inspector J. Reymond',
        officerId: 'GVA-POL-092',
        notes: 'Swiss Federal Customs inspection under Bonded Specie Transit Protocol. Armed escort convoy waiting on tarmac.',
      },
      {
        id: 'cp-6',
        timestamp: '14 Mar 2026, 18:45 CET (Estimated)',
        title: 'Freeport Vault Inward Lodgement & Handover',
        location: 'Geneva, Switzerland',
        facility: 'Geneva Freeport Vault Complex B-12',
        status: 'pending',
        officer: 'Head Vault Custodian L. Favrod',
        officerId: 'GVA-FP-CUST-01',
        notes: 'Custody sign-off, digital weight certificate confirmation, and inward vaulting deposit receipt generation.',
      },
    ],
    telemetry: {
      electronicSeal: {
        id: 'AES-88401-CH',
        status: 'SECURE',
        battery: '98%',
        lastPing: '24s ago',
      },
      gForce: {
        current: 0.08,
        maxRecorded: 0.22,
        threshold: 1.50,
        unit: 'G',
      },
      lightExposure: {
        current: 0.0,
        status: 'SEALED_VAULT',
        unit: 'Lux',
      },
      temperature: {
        current: 19.4,
        min: 18.0,
        max: 21.2,
        unit: '°C',
      },
      gps: {
        lat: 45.4642,
        lng: 9.1900,
        altitude: '38,200 ft',
        speed: '518 kts (960 km/h)',
        satellites: 16,
        signalStrength: '99.4%',
        geofenceStatus: 'CORRIDOR_COMPLIANT',
      },
      escort: {
        code: 'TACTICAL-SWISS-04',
        unit: 'Dual Armed Airborne Escort & Vault Marshals',
        protocol: 'LBMA Gold Standard Specie Escort Class IV',
      },
    },
    manifest: {
      itemType: '999.9 Fine Gold Bullion Bars (LBMA Good Delivery Standard)',
      description: 'Ten (10) x 400 oz Investment-Grade Cast Bullion Bars with London Good Delivery Hallmarks.',
      grossWeight: '400.125 ozt (12.445 kg)',
      netFineWeight: '400.085 ozt Fine Au',
      fineness: '999.9 / 1000 Au',
      sealNumber: 'AES-88401-CH / CH-VAULT-99428',
      assayLab: 'Argor-Heraeus SA Refiners (Mendrisio, Switzerland)',
      assayCertNumber: 'AH-LBMA-2026-99214',
      declaredValue: '$1,180,450.00 USD',
      underwriter: 'Lloyd’s of London Specie & High Value Cargo Syndicate #2003',
      policyNumber: 'LL-SPECIE-8840192-A (Zero Deductible All-Risk)',
      securityTier: 'Level 4 Maximum Sovereign Specie Enclosure',
    },
  },
  {
    id: 'SPECIE-2026-00891',
    trackingNumber: 'AV-ZRH-JFK-41029-S',
    status: 'Bonded Customs Clearance — JFK Inspection',
    statusType: 'customs',
    category: 'Fine Horology & Heritage Archive',
    origin: {
      city: 'Zurich',
      country: 'Switzerland',
      facility: 'Zurich Freeport Vault Facility',
      code: 'ZRH-FP01',
      coords: [47.3769, 8.5417],
    },
    destination: {
      city: 'New York',
      country: 'United States',
      facility: 'Manhattan 5th Ave Private Vaulting Facility',
      code: 'NYC-PV05',
      coords: [40.7128, -74.0060],
    },
    currentLocation: {
      name: 'JFK International Airport — U.S. Customs & Border Protection Vault',
      coords: [40.6413, -73.7781],
      statusText: 'Bonded Hold • Carnet ATA Verification in Progress',
    },
    eta: 'Tomorrow, 10:30 EST',
    dispatchedAt: '13 Mar 2026, 14:00 CET',
    progress: 88,
    transportMode: 'Direct Transatlantic Air-Specie Transport (SWISS LX016)',
    carrierFlightNumber: 'LX-016 / BONDED-SPECIE',
    custodyOfficer: 'Senior Diplomatic Courier H. Vontobel (ID: #ZRH-501)',
    clientCode: 'CLIENT-PATEK',
    checkpoints: [
      {
        id: 'cp-201',
        timestamp: '13 Mar 2026, 14:00 CET',
        title: 'Vault Extraction & Master Clockmaker Verification',
        location: 'Zurich, Switzerland',
        facility: 'Zurich Freeport Vault 7',
        status: 'completed',
        officer: 'H. Vontobel & Dr. A. Benz',
        officerId: 'ZRH-VAULT-88',
        sealId: 'AES-77210-ZRH',
        hash: 'SHA256:3399a9b2c89f10928374a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7',
        notes: 'All 6 museum timepieces inspected under magnification. Movement serial numbers photographed and sealed in nitrogen-purged flight casing.',
      },
      {
        id: 'cp-202',
        timestamp: '13 Mar 2026, 17:45 CET',
        title: 'Flight LX016 Departure Zurich to New York',
        location: 'Zurich Airport (ZRH)',
        facility: 'Swiss International Air Lines Airside Vault',
        status: 'completed',
        officer: 'Security Officer P. Brunner',
        officerId: 'LX-SEC-119',
        sealId: 'AES-77210-ZRH',
        hash: 'SHA256:99887766554433221100aabbccddeeff99887766554433221100aabbccddeeff',
        notes: 'Secured inside climate-stabilized vault compartment (19°C constant, 45% relative humidity).',
      },
      {
        id: 'cp-203',
        timestamp: '14 Mar 2026, 15:20 EST',
        title: 'Arrival at JFK & Secure Tarmac Transfer',
        location: 'Queens, New York',
        facility: 'JFK Air Cargo Building 23 (Bonded)',
        status: 'completed',
        officer: 'Agent B. Gallagher',
        officerId: 'CBP-PORT-NYC',
        sealId: 'AES-77210-ZRH (INTACT)',
        hash: 'SHA256:11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff',
        notes: 'Aircraft landed safely. Armored transport transfer executed under federal surveillance.',
      },
      {
        id: 'cp-204',
        timestamp: '14 Mar 2026, 19:10 EST',
        title: 'U.S. Customs & Border Protection Bonded Inspection',
        location: 'New York, USA',
        facility: 'JFK Bonded Customs Examination Station',
        status: 'current',
        officer: 'Customs Officer R. Miller',
        officerId: 'USCBP-OFFICER-449',
        sealId: 'AES-77210-ZRH',
        hash: 'SHA256:55667788990011223344aabbccddeeff55667788990011223344aabbccddeeff',
        notes: 'Carnet ATA and heritage exemption documentation under final clearance stamp.',
      },
      {
        id: 'cp-205',
        timestamp: '15 Mar 2026, 10:30 EST (Estimated)',
        title: 'Armored Handover to 5th Avenue Vault',
        location: 'New York, USA',
        facility: 'Manhattan 5th Ave Private Vaulting Facility',
        status: 'pending',
        officer: 'Custodian G. Sterling',
        officerId: 'MAN-VAULT-01',
        notes: 'Private collector reception and biometric safe deposit allocation.',
      },
    ],
    telemetry: {
      electronicSeal: {
        id: 'AES-77210-ZRH',
        status: 'SECURE',
        battery: '94%',
        lastPing: '12s ago',
      },
      gForce: {
        current: 0.02,
        maxRecorded: 0.45,
        threshold: 1.00,
        unit: 'G',
      },
      lightExposure: {
        current: 0.0,
        status: 'SEALED_VAULT',
        unit: 'Lux',
      },
      temperature: {
        current: 19.8,
        min: 19.1,
        max: 20.4,
        unit: '°C',
      },
      gps: {
        lat: 40.6413,
        lng: -73.7781,
        altitude: '32 ft',
        speed: '0 kts (Stationary)',
        satellites: 18,
        signalStrength: '98.9%',
        geofenceStatus: 'CORRIDOR_COMPLIANT',
      },
      escort: {
        code: 'US-CONVOY-SPECIE-09',
        unit: 'Dunbar / Brink’s Specialized Armored Ground Unit',
        protocol: 'Armed Dual-Custodian Escort Class V',
      },
    },
    manifest: {
      itemType: 'Fine Horology Archive & Grand Complication Timepieces',
      description: 'Six (6) Historical Complications including Patek Philippe Minute Repeater and Cartier Heritage Platinum Art Deco Pieces.',
      grossWeight: '18.4 kg (Including Pelican Storm High-Impact Nitrogen Cask)',
      netFineWeight: '1,420g Platinum 950 & 18K Yellow/Rose Gold',
      fineness: 'PT950 / 750 (18K) Au',
      sealNumber: 'AES-77210-ZRH / ATA-CARNET-CH-0941',
      assayLab: 'Manufacture Horlogère Patek Philippe SA / Geneva Control',
      assayCertNumber: 'GENEVE-CERT-HOR-2026-44',
      declaredValue: '$4,650,000.00 USD',
      underwriter: 'AXA XL Art & Specie Insurance Global Consortium',
      policyNumber: 'AXA-SPECIE-ART-990214-NYC',
      securityTier: 'Level 5 Maximum Museum Archive Enclosure',
    },
  },
  {
    id: 'BULLION-2026-00344',
    trackingNumber: 'AV-LHR-SIN-11029-B',
    status: 'Delivered — Verified Handover Complete',
    statusType: 'delivered',
    category: 'Precious Metals & Bullion',
    origin: {
      city: 'London',
      country: 'United Kingdom',
      facility: 'LBMA Custody Center (Bank of England Vault Corridor)',
      code: 'LHR-LBMA',
      coords: [51.5074, -0.1278],
    },
    destination: {
      city: 'Singapore',
      country: 'Singapore',
      facility: 'Singapore Le Freeport Vault Sector 4',
      code: 'SIN-LEFP4',
      coords: [1.3521, 103.8198],
    },
    currentLocation: {
      name: 'Singapore Le Freeport Secure High-Security Depository',
      coords: [1.3644, 103.9915],
      statusText: 'Locked in Reinforced Deep Vault • Audit Sealed',
    },
    eta: 'Delivered 04 Mar 2026',
    dispatchedAt: '02 Mar 2026, 09:00 GMT',
    progress: 100,
    transportMode: 'Singapore Airlines Cargo (Flight SQ7973 / Bonded Specie)',
    carrierFlightNumber: 'SQ-7973 / LE-FREEPORT-SPECIE',
    custodyOfficer: 'Chief Inspector C. Sterling & Inspector K. Tan',
    clientCode: 'CLIENT-STERLING',
    checkpoints: [
      {
        id: 'cp-301',
        timestamp: '02 Mar 2026, 09:00 GMT',
        title: 'LBMA Vault Dispatch & Bar Serial Audit',
        location: 'London, UK',
        facility: 'City of London Custodial Vault',
        status: 'completed',
        officer: 'C. Sterling (LBMA Vault Master)',
        officerId: 'LBMA-UK-1092',
        sealId: 'SEAL-UK-88190',
        hash: 'SHA256:77889900aabbccddeeff11223344556677889900aabbccddeeff112233445566',
        notes: 'Ten (10) x 100 oz 999.0 Silver ingots registered on London Good Delivery ledger.',
      },
      {
        id: 'cp-302',
        timestamp: '03 Mar 2026, 14:20 SGT',
        title: 'Singapore Changi Airside Arrival',
        location: 'Singapore',
        facility: 'Changi Airport Airfreight Centre (CAC)',
        status: 'completed',
        officer: 'Agent W. Lim',
        officerId: 'CERTIS-CISCO-88',
        sealId: 'SEAL-UK-88190',
        hash: 'SHA256:990011223344aabbccddeeff556677889900aabbccddeeff1122334455667788',
        notes: 'Certis CISCO armored vehicles escorted cargo directly through customs bonded corridor.',
      },
      {
        id: 'cp-303',
        timestamp: '04 Mar 2026, 11:00 SGT',
        title: 'Final Vault Lodgement & Handover Confirmation',
        location: 'Singapore',
        facility: 'Singapore Le Freeport Vault Sector 4',
        status: 'completed',
        officer: 'Vault Officer K. Tan & Client Signatory',
        officerId: 'LEFP-SIN-004',
        sealId: 'SEAL-FINAL-SIN-00344',
        hash: 'SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        notes: 'Physical assay certificate matched. Bar weight reconciled. Permanent biometric allocation confirmed.',
      },
    ],
    telemetry: {
      electronicSeal: {
        id: 'AES-FINAL-LHR-SIN',
        status: 'SECURE',
        battery: '89%',
        lastPing: 'Delivered (Archived)',
      },
      gForce: {
        current: 0.00,
        maxRecorded: 0.38,
        threshold: 1.50,
        unit: 'G',
      },
      lightExposure: {
        current: 0.0,
        status: 'SEALED_VAULT',
        unit: 'Lux',
      },
      temperature: {
        current: 21.0,
        min: 18.2,
        max: 22.5,
        unit: '°C',
      },
      gps: {
        lat: 1.3644,
        lng: 103.9915,
        altitude: '15 ft (Deep Vault)',
        speed: '0 kts',
        satellites: 0,
        signalStrength: 'Subterranean Vault (Fiber Relay Active)',
        geofenceStatus: 'CORRIDOR_COMPLIANT',
      },
      escort: {
        code: 'CERTIS-TACTICAL-SIN',
        unit: 'Certis CISCO Armed Escort Group',
        protocol: 'Handover Completed & Archival Ledger Committed',
      },
    },
    manifest: {
      itemType: '999.0 Investment Fine Silver Cast Ingots (LBMA Standard)',
      description: 'Ten (10) x 100 ozt Fine Silver Cast Bars stamped with Johnson Matthey refinery hallmarks.',
      grossWeight: '1,000.40 ozt (31.115 kg)',
      netFineWeight: '999.40 ozt Fine Ag',
      fineness: '999.0 / 1000 Ag',
      sealNumber: 'SEAL-FINAL-SIN-00344',
      assayLab: 'Johnson Matthey Refiners (UK) / LBMA Registered',
      assayCertNumber: 'JM-SILVER-UK-88401',
      declaredValue: '$342,000.00 USD',
      underwriter: 'Chubb Global Specie & Marine Transit',
      policyNumber: 'CHUBB-SPECIE-SIN-302194',
      securityTier: 'Level 3 Heavy Precious Ingot Transit Protocol',
    },
  },
  {
    id: 'ROUGH-2026-00912',
    trackingNumber: 'AV-BRU-HND-66104-D',
    status: 'Awaiting Secure Airside Transfer',
    statusType: 'staging',
    category: 'High-Value Gemstones & Rough Diamonds',
    origin: {
      city: 'Antwerp',
      country: 'Belgium',
      facility: 'Antwerp World Diamond Centre (AWDC) High Security Bourse',
      code: 'ANR-AWDC',
      coords: [51.2194, 4.4025],
    },
    destination: {
      city: 'Tokyo',
      country: 'Japan',
      facility: 'Tokyo Ginza Diamond & Jewelry Custody Vault',
      code: 'TYO-GNZ01',
      coords: [35.6762, 139.6503],
    },
    currentLocation: {
      name: 'Brussels International Airport (BRU) Airside Diplomatic Hold',
      coords: [50.9010, 4.4856],
      statusText: 'Staged in Secure Airside Vault • Escort Crew Boarding',
    },
    eta: '20 Mar 2026, 14:00 JST',
    dispatchedAt: '14 Mar 2026, 11:30 CET',
    progress: 24,
    transportMode: 'ANA Cargo Dedicated Specie Locker (Flight NH232)',
    carrierFlightNumber: 'NH-232 / SPECIE-DIRECT',
    custodyOfficer: 'Commander V. Van der Beek (ID: #BEL-DIAM-402)',
    checkpoints: [
      {
        id: 'cp-401',
        timestamp: '14 Mar 2026, 11:30 CET',
        title: 'AWDC Vault Verification & Kimberley Process Audit',
        location: 'Antwerp, Belgium',
        facility: 'AWDC Diamond Bourse Vault',
        status: 'completed',
        officer: 'Inspector P. De Smet & V. Van der Beek',
        officerId: 'KP-CERT-BEL-992',
        sealId: 'KIMBERLEY-SEAL-BE-0912',
        hash: 'SHA256:abcd1234ef567890abcd1234ef567890abcd1234ef567890abcd1234ef567890',
        notes: 'Kimberley Process Certification tamper-proof pouch inspected. All 24 D-Flawless rough diamonds scanned via Sarine laser profiling.',
      },
      {
        id: 'cp-402',
        timestamp: '14 Mar 2026, 14:15 CET',
        title: 'Armored Transfer Antwerp to Brussels Airport',
        location: 'Brussels, Belgium',
        facility: 'BRU Cargo Diplomatic High-Security Enclosure',
        status: 'current',
        officer: 'Security Lead M. Peeters',
        officerId: 'BRU-ESCORT-12',
        sealId: 'AES-88914-ANT',
        hash: 'SHA256:0987654321fedcba0987654321fedcba0987654321fedcba0987654321fedcba',
        notes: 'Flight pallet lockdown completed. Waiting for flight NH232 direct departure to Tokyo Haneda.',
      },
      {
        id: 'cp-403',
        timestamp: '15 Mar 2026, 11:00 JST (Estimated)',
        title: 'Tokyo Haneda Airside Arrival & Customs Quarantine',
        location: 'Tokyo, Japan',
        facility: 'Haneda Airport International Specie Clearance',
        status: 'pending',
        officer: 'Inspector S. Takahashi',
        officerId: 'JPN-CUSTOMS-88',
        notes: 'Ministry of Economy, Trade and Industry (METI) diamond import verification.',
      },
      {
        id: 'cp-404',
        timestamp: '15 Mar 2026, 14:00 JST (Estimated)',
        title: 'Delivery to Ginza Vault & Final Verification',
        location: 'Tokyo, Japan',
        facility: 'Tokyo Ginza Diamond Custody Vault',
        status: 'pending',
        officer: 'Vault Director K. Yamamoto',
        officerId: 'GNZ-VAULT-001',
        notes: 'Final gemological microscope check and transfer to private collector safe deposit box.',
      },
    ],
    telemetry: {
      electronicSeal: {
        id: 'AES-88914-ANT',
        status: 'SECURE',
        battery: '99%',
        lastPing: '18s ago',
      },
      gForce: {
        current: 0.01,
        maxRecorded: 0.15,
        threshold: 1.00,
        unit: 'G',
      },
      lightExposure: {
        current: 0.0,
        status: 'SEALED_VAULT',
        unit: 'Lux',
      },
      temperature: {
        current: 18.5,
        min: 17.8,
        max: 19.2,
        unit: '°C',
      },
      gps: {
        lat: 50.9010,
        lng: 4.4856,
        altitude: '184 ft',
        speed: '0 kts',
        satellites: 14,
        signalStrength: '97.8%',
        geofenceStatus: 'CORRIDOR_COMPLIANT',
      },
      escort: {
        code: 'BEL-SPECIE-COURIER-22',
        unit: 'Federal Diamond Office Escort & Armed Ground Detail',
        protocol: 'Kimberley Process Class A Secure Transit',
      },
    },
    manifest: {
      itemType: 'D-Flawless Rough Gemstone Diamonds (Kimberley Certified)',
      description: 'Parcel of twenty-four (24) uncut gem-quality rough diamonds ranging from 3.20 ct to 14.80 ct.',
      grossWeight: '142.60 carats (28.52 g net diamond weight)',
      netFineWeight: '142.60 ct D-Flawless to VVS1 Grade',
      fineness: 'Type IIa Ultra-Pure Carbon Matrix',
      sealNumber: 'KP-CERT-BEL-0912 / AES-88914-ANT',
      assayLab: 'HRD Antwerp / Gemological Institute of America (GIA)',
      assayCertNumber: 'GIA-HRD-2026-DIAM-449',
      declaredValue: '$2,850,000.00 USD',
      underwriter: 'Berkshire Hathaway Specialty Insurance (Specie)',
      policyNumber: 'BH-SPECIE-DIAM-441092',
      securityTier: 'Level 5 Diplomatic Specie Vaulting Protocol',
    },
  },
]

export const initialVaultHoldings: VaultHolding[] = [
  {
    id: 'VH-GVA-001',
    clientCode: 'CLIENT-STERLING',
    assetTitle: 'LBMA London Good Delivery Gold Bars (400 oz)',
    assetCategory: 'Gold Bullion Bars',
    vaultFacility: 'Geneva Freeport Deep Depository Tier-IV',
    vaultCity: 'Geneva, Switzerland',
    weightOzt: 1200.00,
    grossWeightKg: 37.324,
    fineness: '999.9 Fine Gold',
    hallmark: 'Argor-Heraeus SA Melter & Assayer',
    barSerialNumbers: ['AH-2024-99120', 'AH-2024-99121', 'AH-2024-99122'],
    assayCertNumber: 'ASSAY-AH-CH-99120-22',
    declaredValueUSD: 3521280.00,
    storedSince: '12 Jan 2024',
    status: 'Vaulted',
  },
  {
    id: 'VH-GVA-002',
    clientCode: 'CLIENT-STERLING',
    assetTitle: 'Valcambi Suisse Cast Gold Ingots (1 kg)',
    assetCategory: 'Gold Bullion Bars',
    vaultFacility: 'Geneva Freeport High-Security Vault Complex B-12',
    vaultCity: 'Geneva, Switzerland',
    weightOzt: 321.507,
    grossWeightKg: 10.000,
    fineness: '999.9 Fine Gold',
    hallmark: 'Valcambi Suisse Essayeur Fondeur',
    barSerialNumbers: ['VS-CH-88301', 'VS-CH-88302', 'VS-CH-88303', 'VS-CH-88304', 'VS-CH-88305', 'VS-CH-88306', 'VS-CH-88307', 'VS-CH-88308', 'VS-CH-88309', 'VS-CH-88310'],
    assayCertNumber: 'VALC-2025-CH-88300',
    declaredValueUSD: 943430.00,
    storedSince: '04 Oct 2025',
    status: 'Vaulted',
  },
  {
    id: 'VH-ZRH-001',
    clientCode: 'CLIENT-STERLING',
    assetTitle: 'Royal Canadian Mint 100 oz Gold Specie Bricks',
    assetCategory: 'Gold Bullion Bars',
    vaultFacility: 'Zurich Kloten Safe Depository (ZRH-AIR-V1)',
    vaultCity: 'Zurich, Switzerland',
    weightOzt: 500.00,
    grossWeightKg: 15.551,
    fineness: '999.9 Fine Gold',
    hallmark: 'Royal Canadian Mint Assayer Seal',
    barSerialNumbers: ['RCM-AU-4401', 'RCM-AU-4402', 'RCM-AU-4403', 'RCM-AU-4404', 'RCM-AU-4405'],
    assayCertNumber: 'RCM-CERT-2025-AU44',
    declaredValueUSD: 1467200.00,
    storedSince: '18 Nov 2025',
    status: 'Vaulted',
  },
  {
    id: 'VH-GVA-003',
    clientCode: 'CLIENT-PATEK',
    assetTitle: 'Patek Philippe Grandmaster Chime Ref. 6300G & Archive Masterworks',
    assetCategory: 'Horological High Specie',
    vaultFacility: 'Geneva Freeport Vault B-12 Private Alcove',
    vaultCity: 'Geneva, Switzerland',
    weightOzt: 64.30,
    grossWeightKg: 2.000,
    fineness: '18K White Gold / Platinum & Grand Feu Enamel',
    hallmark: 'Patek Philippe Geneva Seal (Poinçon de Genève)',
    barSerialNumbers: ['PP-6300G-001', 'PP-ARCHIVE-5175R', 'PP-5004P-SPEC'],
    assayCertNumber: 'PP-ARCHIVE-HERITAGE-CERT-904',
    declaredValueUSD: 6850000.00,
    storedSince: '20 May 2024',
    status: 'Vaulted',
  },
  {
    id: 'VH-SIN-001',
    clientCode: 'CLIENT-PATEK',
    assetTitle: 'Heritage Pocket Chronometers & Calibre 89 Reserve Specie',
    assetCategory: 'Horological High Specie',
    vaultFacility: 'Singapore Freeport Changi Specie Depository',
    vaultCity: 'Singapore',
    weightOzt: 48.22,
    grossWeightKg: 1.500,
    fineness: 'Yellow Gold 18K & Rare Complications',
    hallmark: 'Geneva Observatory Certified Chronometer',
    barSerialNumbers: ['PP-CAL89-RES-01', 'PP-POCK-1898-V'],
    assayCertNumber: 'COSC-GENEVA-HIST-778',
    declaredValueUSD: 4200000.00,
    storedSince: '15 Aug 2025',
    status: 'Vaulted',
  },
]

